name: 'lambda CICD(Test)'
on:
  pull_request:
    branches:
      - main
env:
  LambdaFunctionName: "lv-security-lambda-security-alert-dev"
jobs:  
  deploy_lambda:
    name: 'Deploy a lambda function(Test)'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup AWS credentals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Python modules
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt --target ./src
  
      - name: create zip
        working-directory: src
        run: zip -r ../package.zip .

      - name: update function code
        run: aws lambda update-function-code --function-name ${{env.LambdaFunctionName}} --zip-file fileb://package.zip --no-publish

  test_lambda:
    name: 'test a lambda function'
    needs: deploy_lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Setup AWS credentals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: "TEST: shared accounts security alert test."
        run: |
          aws lambda invoke --function-name ${{env.LambdaFunctionName}} --payload fileb://test_resuces/test_payload_777777777777.json response1.json
          echo "response1.json" && cat response1.json
          grep 200 response1.json
      - name: "TEST: Resource accounts security alert test."
        run: |
          aws lambda invoke --function-name ${{env.LambdaFunctionName}} --payload fileb://test_resuces/test_payload_888888888888.json response2.json
          echo "response2.json" && cat response2.json
          grep 200 response2.json
      - name: "TEST: other accounts security alert test."
        run: |
          aws lambda invoke --function-name ${{env.LambdaFunctionName}} --payload fileb://test_resuces/test_payload_999999999999.json response3.json
          echo "response3.json" && cat response3.json
          grep 200 response3.json