name: 'lambda CICD(Deploy)'
on:
  push:
    branches:
      - main
env:
  LambdaFunctionName: "lv-security-lambda-security-alert-dev"
jobs:  
  deploy_lambda:
    name: 'Deploy a lambda function(Production)'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup AWS credentals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: create zip
        working-directory: src
        run: zip -r ../package.zip .

      - name: update function code
        run: aws lambda update-function-code --function-name ${{env.LambdaFunctionName}} --zip-file fileb://package.zip --no-publish
      
